import unittest

from katas.kyu_6.rna_to_protein import protein


class ProteinTestCase(unittest.TestCase):
    def test_equals(self):
        self.assertEqual(protein('AUG'), 'M')

    def test_equals_2(self):
        self.assertEqual(protein('AUGUGA'), 'M')

    def test_equals_3(self):
        self.assertEqual(protein('AUGGUUAGUUGA'), 'MVS')

    def test_equals_4(self):
        self.assertEqual(protein('UGCGAUGAAUGGGCUCGCUCC'), 'CDEWARS')

    def test_equals_5(self):
        self.assertEqual(protein(
            'AUGUCCUUCCAUCAAGGAAACCAUGCGCGUUCAGCUUUCUGA'), 'MSFHQGNHARSAF')

    def test_equals_6(self):
        self.assertEqual(protein(
            'AUGCUUCAAGUGCACUGGAAAAGGAGAGGGAAAACCAGUUGA'), 'MLQVHWKRRGKTS')

    def test_equals_7(self):
        self.assertEqual(protein(
            'AUGGCGUUCAGCUUUCUAUGGAGGGUAGUGUACCCAUGCUGA'), 'MAFSFLWRVVYPC')

    def test_equals_8(self):
        self.assertEqual(protein(
            'AUGCAGCUUUCUAUGGAGGGUAGUGUUAACUACCACGCCUGA'), 'MQLSMEGSVNYHA')

    def test_equals_9(self):
        self.assertEqual(protein(
            'AUGCUAUGGAGGGUAGUGUUAACUACCACGCCCAGUACUUGA'), 'MLWRVVLTTTPST')

    def test_equals_10(self):
        self.assertEqual(protein(
            'AUGUAUCCUUCCAUCAAGGAAACCAUGCGCGUUCAGCUUUCUAUGGAGGGUAGUGUUAACUA'
            'CCACGCCUUCAAGUGCACUGGAAAAGGAGAGGGAAAACCAUACGAAGGCACCCAAAGCCUGA'
            'AUAUUACAAUAACUGAAGGAGGUCCUCUGCCAUUUGCUUUUGACAUUCUGUCACACGCCUUU'
            'CAGUAUGGCAUCAAGGUCUUCGCCAAGUACCCCAAAGAAAUUCCUGACUUCUUUAAGCAGUC'
            'UCUACCUGGUGGUUUUUCUUGGGAAAGAGUAAGCACCUAUGAAGAUGGAGGAGUGCUUUCAG'
            'CUACCCAAGAAACAAGUUUGCAGGGUGAUUGCAUCAUCUGCAAAGUUAAAGUCCUUGGCACC'
            'AAUUUUCCCGCAAACGGUCCAGUGAUGCAAAAGAAGACCUGUGGAUGGGAGCCAUCAACUGA'
            'AACAGUCAUCCCACGAGAUGGUGGACUUCUGCUUCGCGAUACCCCCGCACUUAUGCUGGCUG'
            'ACGGAGGUCAUCUUUCUUGCUUCAUGGAAACAACUUACAAGUCGAAGAAAGAGGUAAAGCUU'
            'CCAGAACUUCACUUUCAUCAUUUGCGUAUGGAAAAGCUGAACAUAAGUGACGAUUGGAAGAC'
            'CGUUGAGCAGCACGAGUCUGUGGUGGCUAGCUACUCCCAAGUGCCUUCGAAAUUAGGACAUA'
            'ACUGA'),
            'MYPSIKETMRVQLSMEGSVNYHAFKCTGKGEGKPYEGTQSLNITITEGGPLPFAFDILSHAF'
            'QYGIKVFAKYPKEIPDFFKQSLPGGFSWERVSTYEDGGVLSATQETSLQGDCIICKVKVLGT'
            'NFPANGPVMQKKTCGWEPSTETVIPRDGGLLLRDTPALMLADGGHLSCFMETTYKSKKEVKL'
            'PELHFHHLRMEKLNISDDWKTVEQHESVVASYSQVPSKLGHN'
        )


if __name__ == '__main__':
    unittest.main()
